name: traffic-cam
dependencies:
  - python=3.6
  - pip
  - pip:
    - opencv-python
    - numpy
    - yolo34py  # requires pkg-config, e.g. 'sudo apt install pkg-config#'
    - matplotlib
    # dev
    - black
    - jupyter
    - pylama
    - rope
